<?php

return [
    'disable' => env('CAPTCHA_DISABLE', false),
    'characters' => [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
    ],


    'fontsDirectory' => dirname(__DIR__) . '/vendor/mews/captcha/assets/fonts',
    // 'fontsDirectory' => resource_path('assets/fonts'), 
    'bgsDirectory' => dirname(__DIR__) . '/vendor/mews/captcha/assets/backgrounds',
    // 'bgsDirectory' => resource_path('assets/bgs'),
    

    'default' => 'flat',

    'cache' => ['store' => 'file', 'key' => 'captcha'],

    'flat' => [
        'length' => 5,
        'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
        'width' => 120,
        'height' => 36,
        'math' => false,
        'quality' => 90,
        'lines' => 0,
        'bgImage' => false,
        'bgColor' => '#F3F4F6',
        'contrast' => 0,
        // Hapus 'type' => 'math',
    ],

    'math' => [
        'length' => 5,
        'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
        'width' => 120,
        'height' => 36,
        'math' => true,
        'quality' => 90,
        'lines' => 0,
        'bgImage' => false,
        'bgColor' => '#ecf0f1',
        'contrast' => 0,
    ],  
];
